[center][style b size=18px]Java Containers[/style]
[size=14px]By ashura_temps © 2025[/size][/center]
[hr]
[b]not yet updated containers[/b]
[list]
[*]Command Block - i plan on doing this one soon[/*]
[*]Structure Block[/*]
[*]Jigsaw Block[/*]
[*]and possibly others[/*]
[/list][hr]
[url=/texture-pack/dark-mode-java-containers-mcbe-mcpe-v1-7/][b]Dark mode ---> Java-Containers Dark Mode[/b][/url]

[hr]
[style b size=16px]Notes[/style]
[list]
[*][b]This pack is still in development so expect texture improvements and bug fixes.[/b][/*]
[*][b]Report issues or track updates on Discord[url=https://discord.gg/sFnE7zv75t] Join Here[/url][/b][/*]
[*][b]you can leave feedback on [url=https://github.com/fumeko-ts/java-edition-containers-mcbe/discussions]Github[/url] or on [url=https://discord.gg/sFnE7zv75t]discord[/url] or in the comments here.[/b][/*]
[/list]
[hr]
[style b size=16px]Permissions & Usage
[/style]
[b]Allowed[/b]
[list]
[*]Share the pack [b]only[/b] by linking to this PMC page.[/*]
[*]Create videos/reviews if clear credit is given to [b]ashura_temps[/b] and the [b]official pmc download link[/b] is included.[/*]
[/list]
[b]Not Allowed[/b]
[list=1]
[*]Converting/porting Java textures to Bedrock using my texture pack.[/*]
[*]Redistributing, reuploading, or sharing my files elsewhere.[/*]
[*]Modifying UI files or code.[/*]
[*]Using MediaFire/direct links/mirrors.[/*]
[/list]
[hr]
[style b size=16px]Credits[/style]
[list]
[*][b]Map/Schematic in the Background is by:[/b] [url=/member/arion_grey][b]Arion_Grey[/b][/url]
[url=/project/overlords-thronehall-nazarick-by-arion/][b]Overlord's Thronehall Schematic[/b][/url][/*]
[/list]
[hr]
[style b size=16px]Legal Notice[/style]
© ashura_temps, 2025. All Rights Reserved.
[list]
[*]"All Rights Reserved" means I retain full copyright control - [b]no one[/b] may redistribute, modify, or use my work beyond the permissions explicitly granted above unless i have given my permission.[/*]
[*]By downloading, you agree to the above [/*]
[/list]